### ISSUE TITLE
support API for controlling the table resizing

### ISSUE THREAD

**Issue by igorlino** [tympanix/angular-table-resize#10]
Once a table is resized its hard to control some aspects of it.
It would be very nice to:

- Have detection of methods when resizing starts and ends. So callbacks like:  onResizeStarted, onResizeInProgress, onResizeEnded
- Ability to remove the storage information
- Ability to explicitly do not save storage information at all. (even if all id's are present)
- Ability to reset the table size to original

As inspiration, one can look at the angular-seletize component. (https://github.com/opsolve/angular-selectize). In that component they pass an object with the desired options and callbacks.

The callbacks of selectize looks like this:
https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md

As inspiration for events one could look at https://github.com/Reklino/angular-resizable
it applies to containers, not tables, but its interesting to see the type of information that they show in case of an event. I find the selectize API nicer.

**Comment by tympanix** [comment]
I have had a little reboot of the project. Fixed in df96e2d897f727877966c387546cc1c6dccf56ea released in v2.0.0

**Comment by igorlino** [comment]
Nice !!!
