### ISSUE TITLE
Strange style error in Chrome on macOS

### ISSUE THREAD

**Issue by lkebin** [tympanix/angular-table-resize#14]
![imgur](http://imgur.com/download/jJTfkry)
Like that. When I resize column, the border style is bad.
The strange that it will be occur in the Chrome on macOS (Macbook Pro 13" Retina screen). It doesn't appear with external monitor. and doesn't appear on iMac Retina screen. It is appear on Macbook Pro 13" build-in monitor only....

If you have the device you can have a try with the following link.

[jsfiddle](https://jsfiddle.net/lkebin/w1xaq2jk/)

**Comment by tympanix** [comment]
This is a rendering bug/optimisation in Chrome specifically on laptops to save power/performance. Chrome is known to "cut corners" when it comes to re-rendering specific elements or styles. By applying a transform property to your element, you can force chrome to re-render in most scenarios.

I have had luck with using `opacity: 0.99;`. Try it yourself on the css styles for the `table` tag. Alternatively you can try something like `transform: translateZ(0);` - whichever works for you.

**Comment by lkebin** [comment]
@Tympanix  Thanks!
It is works with `opacity:0.99`.
