### ISSUE TITLE
adding a new column dinamically the resize is not working on it 

### ISSUE THREAD

**Issue by pam81** [tympanix/angular-table-resize#15]
I have a column hidden with ng-if  when col.location = false
 <th id="location" ng-if="col.location">Location </th>

when col.location is true I can see the location column but I can't resize it.

**Comment by tympanix** [comment]
This is very similar to #9 and is something the module does not support since it only evaluates the columns once when linking the directive. You may try the experimental [v2.0](https://github.com/tympanix/angular-table-resize/tree/v2.0) branch, although it has not been published officially yet.

**Comment by tympanix** [comment]
I have patched this using the approach mentioned in #9. It will behave a little funky when using the `Basic` resizer (because the column widths are static and the columns are manipulated).

**Comment by tympanix** [comment]
I have now also fixed the issue with the `Basic` resizer in v1.0.12. Cheers.

**Comment by pam81** [comment]
great! good fix! 
anyway I found another solution use ng-show to hide/show the column instead of ng-if.
