### ISSUE TITLE
bower install doesn't automatically add the dependency to index.html

### ISSUE THREAD

**Issue by pam81** [tympanix/angular-table-resize#16]
I run 
bower install angular-table-resize 
but it doesn't add the css and js dependencies to index.html

**Comment by tympanix** [comment]
The command `bower install` only adds the package to the `bower_components` directory. You will have to link the css and js file yourself i your `index.html` as instructed in the [setup](https://github.com/tympanix/angular-table-resize#setup). Am I missing something or does this answer your question?
