### ISSUE TITLE
Demo doesn't work?

### ISSUE THREAD

**Issue by miliu99** [tympanix/angular-table-resize#17]
It doesn't resize for me (in chrome) at least.

**Comment by tympanix** [comment]
It does work. You need to drag the handle (invisible) in the column headers (to the left of the column text). I figured this would result in some misconception. I will make sure to make it more clear

**Comment by miliu99** [comment]
After reading your comment, it still took me a while to finally figure it
out. I think a visible drag line would make it a real "Demo". Thanks.
