### ISSUE TITLE
directive not recognised

### ISSUE THREAD

**Issue by robeverett** [tympanix/angular-table-resize#21]
I cannot get my controller to recognise the module: rzTable, whether I reference resize-table-directive in my view html with a script tag: <script src="angular-table-resize.js"></script> or writing the module name in square brackets in the controller: angular.module('myApplication', ['rzTable'])
I get the angular error page of import module not recognised

I've downloaded the folder angular-table-resize and it is in the node_modules folder of my angularJS app.
Should I move it to another folder in my app ?

I've tried to follow the instructions : #### Example:
```html
<table rz-table id="myTable">
  <thead>
    <th ng-repeat="col in columns" rz-col="col"></th>
  </thead>
  ...
</table>
```

but the rz-table tag is not recognised.

Do I need an @import statement somewhere ?

**Comment by tympanix** [comment]
The script tag in the readme is simplified. You need a valid path to the file. In the case of installing with npm it would look something like:

```html
<script src="node_modules/angular-table-resize/dist/angular-table-resize.js"></script>
```
Are you sure you are using a valid path?

**Comment by robeverett** [comment]
Thanks
Actually, thinking about it, couldn't I just copy (or cut) the angular-table-resize folder and its content from node_modules into my public/javascripts folder ? Although most of the javascripts in that folder are mnified!

**Comment by tympanix** [comment]
You could. But I would not recommend it as your dependencies would then not be managed by npm. I would highly suggest you to take a look at [webpack](https://webpack.js.org) (or some similar tool) which will extract, process and bundle your dependencies into production artefacts.

**Comment by tympanix** [comment]
Btw there are also minified versions available in the `dist` folder.

**Comment by robeverett** [comment]
So can I just reference a minified version directly in my html where I have the table with a script tag ??

**Comment by tympanix** [comment]
Yes, if you want the minified version you may do that. You can choose either one of them, functionally they are the same. I would still suggest webpack though, which can also do the minification for you.
