### ISSUE TITLE
Missing index.js

### ISSUE THREAD

**Issue by vijaybhorems** [tympanix/angular-table-resize#4]
I did bower install and can see that angular-table-resize folder in download location.

The package.json mentions index.js as the value of main, but i could not find it in the folder hierarchy. 

Finally, i am not able to inject the 'ngTableResize' module into my application.

Has anybody found this issue?

Thanks!

**Comment by vijaybhorems** [comment]
I think, there is an alternative way where bower.json has main attribute mapped to index.html. 

Rest of the libraries in my app are using jQuery 2.1.4, so i am trying to use gulp main-bower-files override feature to specify jQuery version 3.1.0.

Thanks!

**Comment by tympanix** [comment]
Hi vijaybhorems.

Don't mind the _main_ entry i either the _package.json_ nor _bower.json_ file as they have been auto generated. I will be sure to clean this up.

If you simply want to use the module you should only care about the files in the _dist_ folder. The module has only been tested with jQuery version 3.0.0 so be sure to update if possible.

Alternatively please look at the source files for the demo application. They can be found in the [gh_pages](https://github.com/Tympanix/angular-table-resize/tree/gh-pages) branch for a minimal implementation example.

Get back to me if you have further questions :)
