### ISSUE TITLE
please change the dependency of jQuery to jquery (Lowercase)

### ISSUE THREAD

**Issue by rockydd** [tympanix/angular-table-resize#5]
Most of the libraries's set the dependency of **jQuery** with lowercase: (**jquery**). But in this project, it use jQuery. That cause a problem, that when I run `bower install`, it will think jQuery is different with jquery, so it just install it, and unfortunately, in OSX, the folder name is incase-sensitive. So the jquery is overwritten by jQuery.

Then when you run `bower list`, it will complain jquery is not installed. If you run `npm install` again, the jquery will install jQuery, then jQuery will be displayed as not install. That will be a dead loop. 

So, please change it to lower case. It will help me out. Thanks.

**Comment by rockydd** [comment]
BTW, nice work of this directive.

**Comment by tympanix** [comment]
Thank you for finding the bug. I have seen your fork - you are more than welcome to send me a pull request with your fix :+1:

**Comment by rockydd** [comment]
I have create a PR for this. :)
